<?php
$cmsPages = Mage::getModel('cms/page')->getCollection()
    ->addStoreFilter(Mage::app()->getStore()->getId())
    ->addFieldToFilter('is_active',1)
    ->addFieldToFilter('identifier', array(
            array(
                'nin' => array(
                    'home',
                    'no-route',
                    'enable-cookies',
                    'empty'
                )
            )
        )
    );
?>

<?php //var_dump(Mage::getModel('cms/page')->getCollection()->addStoreFilter(Mage::app()->getStore()->getId())) ?>
<style type="text/css">
    #cms-navigation a.active { font-weight: bold; }​
</style>
<script type="text/javascript">
    jQuery(document).ready(function() {
        var url = window.location.pathname,
            urlRegExp = new RegExp(url.replace(/\/$/,'') + "$");
        jQuery('#cms-navigation a').each(function(){
            if(urlRegExp.test(this.href.replace(/\/$/,''))){
                jQuery(this).addClass('active');
            }
        });
    });
</script>
<div class="block">
    <div class="block-title">
        <strong><span><?php echo $this->__('Page Navigation');?></span></strong>
    </div>
    <div class="block-content">
        <ul id="cms-navigation" class="accordion accordion-style1 vertnav vertnav-side clearer">
            <?php
            foreach($cmsPages as $_cms):
                $page = $_cms->getData();
                ?>
                <li class="nav-item level0">
                    <a href="<?php echo $this->getBaseUrl() . $page['identifier']; ?>"><?php echo $page['title']; ?></a>
                </li>
            <?php
            endforeach;
            ?>

        </ul>
    </div>
</div>