<div id="login-popup" class="popup" style="display:none;">
    <a href="#" class="popup-close" id="popup-close">x</a>
    <div class="popup-arrow"></div>
    <div class="popup-heading"><h2 id="popup-heading"><?php echo $this->__('Login or Create an Account') ?></h2></div>
    <div class="popup-content" id="popup-content">
        <div class="requare"><p class="required"><?php echo $this->__('* Required Fields') ?></p></div>
            <div class="col2-set">
                <div class="col-1 new-users">
                    <div class="content">
                        <form action="<?php echo $this->getUrl('customer/account/loginPost') ?>" method="post" id="login-form-popup">
                            <ul class="form-list">
                                <li>
                                    <label for="email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                                    <div class="input-box">
                                        <input type="text" name="login[username]" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                                    </div>
                                </li>
                                <li>
                                    <label for="pass" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                                    <div class="input-box">
                                        <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                                    </div>
                                </li>
                            </ul>
                            <div class="buttons-set">
                                <button type="submit" style="float: left;" class="button green" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                                <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="fogot-link"><?php echo $this->__('Forgot Your Password?') ?></a>
                                <span id="login-form-popup-ajax" class="ajax-loader" style="display:none"></span>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-2 registered-users">
                    <div class="content">
                        <form action="<?php echo $this->getUrl('customer/account/createPost') ?>" method="post" id="register-form-popup">

                            <ul class="form-list">
                                <li>
                                    <label for="firstname" class="required"><?php echo $this->__('First name') ?><em>*</em></label>
                                    <div class="input-box">
                                        <input type="text" name="firstname" id="firstname" class="input-text required-entry" />
                                    </div>
                                </li>
                                <li>
                                    <label for="lastname" class="required"><?php echo $this->__('Last name') ?><em>*</em></label>
                                    <div class="input-box">
                                        <input type="text" name="lastname" id="lastname" class="input-text required-entry" />
                                    </div>
                                </li>
                                <li>
                                    <label for="email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                                    <div class="input-box">
                                        <input type="text" name="email" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                                    </div>
                                </li>
                                <li>
                                    <label for="pass" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                                    <div class="input-box">
                                        <input type="password" name="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                                    </div>
                                </li>
                                <li>
                                    <?php // honey pot protection. Don't delete this field ?>
                                    <label for="site" class="required">Site</label>
                                    <div class="input-box">
                                        <input type="text" name="site" class="input-text" title="Site" id="site" />
                                    </div>
                                </li>
                            </ul>

                            <div class="buttons-set">
                                <button type="submit" class="button" title="<?php echo $this->__('Create an Account') ?>" name="send" id="send2"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                                <span id="register-form-popup-ajax" class="ajax-loader" style="display:none"></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript"><!--
            var loginForm = new AjaxLogin('login-form-popup'),
                registerForm = new AjaxLogin('register-form-popup');

            loginForm.form.setAttribute('action', "<?php echo $this->getUrl('ajax/customer_account/loginCustomer') ?>");
            registerForm.form.setAttribute('action', "<?php echo $this->getUrl('ajax/customer_account/createCustomer') ?>");
            registerForm.form.site.parentNode.parentNode.style.display = 'none';
        //--></script>
    </div>
</div>
